name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install main deps
        run: yarn
      - name: Initialize
        run: yarn lerna bootstrap
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        env:
          EXTERNAL_SERVER_URL: http://localhost:3001
          INTERNAL_SERVER_URL: http://localhost:3001
          SERVER_PORT: 3001
          CLIENT_PORT: 3000
        run: yarn build
